### ISSUE TITLE
the plugin should use cache_manager

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_openstreetmap#15]
zp_openstreetmap should register its own thumbs size, using cache_manager.

**Comment by acrylian** [comment]
It actually does that or is there any mistake?

![bildschirmfoto 2018-03-21 um 13 38 06](https://user-images.githubusercontent.com/2474309/37710178-231012be-2d0d-11e8-9f9a-51d6552be8da.jpg)

**Comment by vincent3569** [comment]
oups sorry, my eyes are closed this morning
