### ISSUE TITLE
add control layer option

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_openstreetmap#19]
hi

il would be a nice improvement if you could implement control layer option.
see documentation of leafletjs here:
https://leafletjs.com/reference-1.3.0.html#control-layers
https://leafletjs.com/examples/layers-control/

**Comment by acrylian** [comment]
I took a look and I am not sure how to do this really easily. Between which layers would you want to switch? Different map tiles? That would surely be possible with another full set of checkbox options to set which map tiles should be allowed. Other layers like markers etc. would have to be set manually anyway. The idea was to keep the plain plugin rather simple as leaflet has far too many possibilities and use the class or js directly for more individual settings.

**Comment by acrylian** [comment]
So you like to be able to switch between map tiles (if more than two selected for it naturally only) and switch markers on/off?

I will postpone this for sometime later.

**Comment by vincent3569** [comment]
only switch between map tiles.
switch markers on/off makes no sense for me, as the plugin is made to show where the picture has been made, so we need a marker.

**Comment by acrylian** [comment]
Okay, it's consider. Have to look how much time I get before this is moved into ZP itself.
