### ISSUE TITLE
add option for Leaflet.markercluster

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_openstreetmap#20]
hi

it would be a nice improvement if you could implement option for show/hide the limits of a cluster when mouse over on a cluster (it is true by default).

see documentation of leafletjs here:
https://github.com/Leaflet/Leaflet.markercluster#all-options

**Comment by acrylian** [comment]
Which option do you mean exactly, there are several referring to bounds?

**Comment by vincent3569** [comment]
as far I can see, this option:
showCoverageOnHover: When you mouse over a cluster it shows the bounds of its markers.

I don't like this behavior of leaflet.js, so if you can add this option to not display limits it would be perfect.

**Comment by acrylian** [comment]
I have to admit I use leaflet on standalone (non zp) map with clusters and I never noticed any bounds or actually know what this is… Clusters just zoom in/expand on click as far as I noticed and I didn't set this option at all.  Do you have an example for me where I can see this?

**Comment by vincent3569** [comment]
yes of course, as usual, my test site: http://test.vincentbourganel.fr/pages/map-osm/
have a look on 502 pictures in France: when mouse over, you can see the limits of the cluster in blue

**Comment by acrylian** [comment]
Ah, of course I know that now. Probably my clusters have just not that range to trigger this. I agree that option makes sense.
