### ISSUE TITLE
mapbox tile doesn't work

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_openstreetmap#21]
hi

as requested, I create a account on https://www.mapbox.com/account/
despite that, mapbox tile doesn't work: only green screen and a link to leaflet are displayed.

and all-in-one: think to update your readme.md to add the new script used:
leaflet-providers plugin: https://github.com/leaflet-extras/leaflet-providers

**Comment by vincent3569** [comment]
as far I can see, mapbox credentials are not used in the js map init.

````
		switch ($maptile[0]) {
			case 'Mapbox':
				return "L.tileLayer.provider('" . $this->maptiles . "', {"
								. "id: '" . getOption('osmap_mapbox_id') . "',"
								. "accessToken: '" . getOption('osmap_mapbox_accesstoken') . "'"
								. "}).addTo(map);";
````

**Comment by vincent3569** [comment]
still doesn't work :-(

I have now these errors in my console:

"NetworkError: 407 Proxy Authentication Required - http://api.tiles.mapbox.com/v4/vincent3569/3/2/2.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
2.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/3/3.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
3.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/3/2.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
2.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/4/2.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
2.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/2/3.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
3.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/4/3.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
3.png?a...BioWxZA
"NetworkError: 407 Proxy Authentication Required - http://s7.addthis.com/l10n/client.fr.min.json"
client....in.json
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/3/1.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
1.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/2/1.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
1.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/1/2.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
2.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569/3/4/1.png?access_token=pk.eyJ1IjoidmluY2VudDM1NjkiLCJhIjoiY2poYWx4NGk4MDFpYjM2bnZmZGE4ZmQ2bCJ9.rm8enR9d-cWSeWmBioWxZA"
1.png?a...BioWxZA
"NetworkError: 404 Not Found - http://api.tiles.mapbox.com/v4/vincent3569

**Comment by acrylian** [comment]
If I quickly review their API docs it might be that the url leaflet-providers generates is not correct:
https://www.mapbox.com/api-documentation/#reading-this-documentation

Your examples show  http://api.tiles.mapbox.com/v4/vincent3569/3/4/1.png(…) urls while they list https://api.mapbox.com/v4/mapbox.dark/-76.9,38.9,5/400x200.png?(…). 

So maybe that's it. But that

**Comment by vincent3569** [comment]
yeah!
I was thinking that requested ID was my account ID, but it is MapBox Map ID!
I replace `vincent3569` by `mapbox.satellite` and it works fine now.

**Comment by vincent3569** [comment]
knowing that, there is a way to avoid confusion and manage mabpox id as other tile name and not manage an ID option.
I willm ake a pull request.

**Comment by acrylian** [comment]
Interesting, I think this is acutally also an issue of the leaflet providers plugin itself and it's documentation. I had to extract the tile info from the js file to use it for the options. There indeed the id is hardcoded as "streets" but there are no variants as you added included as on the other map defines (see Stamen below)

![bildschirmfoto 2018-05-18 um 11 05 00](https://user-images.githubusercontent.com/2474309/40226208-554601fc-5a8b-11e8-83bf-53148e44ed22.jpg)
