### ISSUE TITLE
On Monday, July 11, 2016, our direct tile access to MapQuest legacy maps will be discontinued

### ISSUE THREAD

**Issue by mazze77** [acrylian/zp_openstreetmap#6]
Hi,

no Mapdata on the Website will be shown.
Modernization of MapQuest results in changes to direct tile access
[http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/](http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/)

![mapquest](https://cloud.githubusercontent.com/assets/8436546/17127480/369f2f6e-5306-11e6-9572-a965ebe4502f.PNG)

**Comment by acrylian** [comment]
MapQuestOpen tile styles have been removed from the plugin so only free tile styles are featured now.
