### ISSUE TITLE
thumb with poor quality

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_openstreetmap#7]
hi Malte
thanks for your plugin!
a possible improvement:
you use the internal thumb of the pictures with this function (line 455):
`<img src='" . $image->getThumb() . "' alt='' />`

but the internal quality of these thumbs is very poor.
maybe you should create a specific thumb as it is done in original googlemap plugin:
`<img src="' . getCustomImageURL(150, NULL, NULL, NULL, NULL, NULL, NULL, true) . '" alt="" />`

**Comment by acrylian** [comment]
Sorry for the late reply. I constantly miss tickets on repos as they don't appear on the overview list…

The thumb quality actually is the one your set on the general image options. Or do you mean just the size? That also is the one set on these options.
